---
title: "R Notebook on National Opioid Death Simple EDA"
output:
  pdf_document: default
  html_notebook: default
---
## ISABEL METZGER
Making graphs used in glimpse of US opioid deaths/ state rates
```{r, include=FALSE}
library(readr)
X2015_death_data <- read_csv("~/R_STUDIO_FALL_2017_PDA/hw2-izzykayu/2015-death-data.csv")
Xdeath_2013_2014 <- read_csv("~/R_STUDIO_FALL_2017_PDA/hw2-izzykayu/drug_poisoning_deaths_by_state-_us_2013_2014-v7.csv")
mycols3 <- c("#c6d4e1", "#2f2016", "#fcfaea", "#456789")
library(tidyverse)
library(tidytext)
library(stringr)
library(DT)
death2015 <- X2015_death_data %>% dplyr::select(-X5, -X6, -X7, -X8)
colnames(death2015) <- c("state", "Range.2015", "Rate.2015", "Deaths.2015")
colnames(Xdeath_2013_2014) <- c("state", "Rate.2014", "Deaths.2014", "Range.2014", "Rate.2013", "Deaths.2013", "Range.2013", "Change", "Significant")
```

```{r, message=FALSE, warning=FALSE}
library(noncensus)
data("states")
overdosedeath <- death2015 %>% left_join(states, by="state")
fullopioiddeathset_2013_2015 <- overdosedeath %>% right_join(Xdeath_2013_2014)

library(ggthemes)
# re-order levels
reorder_size <- function(x) {
        factor(x, levels = names(sort(table(x), decreasing = TRUE)))
}

head(fullopioiddeathset_2013_2015,2)
longset <- fullopioiddeathset_2013_2015 %>% gather(Deaths.2013,Deaths.2014,Deaths.2015, key="Year", value="Deaths")
```
```{r}
mycols3
```

```{r}
cols <-c("#9D1F2F","#d6604d", "#92c5de","#0571b0")
longset$year <- longset$Year
longset$Year <- gsub("Deaths.2013", 2013, longset$Year)
longset$Year <- gsub("Deaths.2014", 2014, longset$Year)
longset$Year <- gsub("Deaths.2015", 2015, longset$Year)
 res <- longset %>% dplyr::select(Year, Deaths, region)
 res$region <- as.character(res$region)
 res$Year <- as.numeric(res$Year)
  colnames(res) <- c("Year", "Opioid.Deaths", "Region")
 res %>% head(5)
# par(mar=c(5.1, 4.1, 4.1, 7.1), xpd=TRUE)
# barplot(prop, col=heat.colors(length(rownames(prop))), width=2, beside=TRUE)
# legend("topright",inset=c(-0.25,0), fill=heat.colors(length(rownames(prop))), legend=rownames(data))

# longset %>% ggplot(aes(region, Deaths)) + geom_point(aes(col=state)) + facet_wrap(~Year)
longset %>% filter(Year==2013) %>% mutate(state = state, Deaths)%>% ggplot(aes(state,Deaths)) + geom_col(aes(fill=region)) + coord_flip() + theme_classic() +
        theme(axis.text = element_text(hjust = 1, size=6.7, angle=20)) + scale_fill_manual(values=cols)
longset %>% filter(Year==2014) %>% mutate(state = reorder(state, Deaths))%>% ggplot(aes(state, Deaths)) + geom_col(aes(fill=region)) + coord_flip() + theme_classic() +
        theme(axis.text = element_text(hjust = 1, size=6.7, angle=20)) + scale_fill_manual(values=cols)
longset %>% filter(Year==2015) %>% mutate(state = reorder(state, Deaths))%>% ggplot(aes(state, Deaths)) + geom_col(aes(fill=region)) + coord_flip() + theme_classic() +
        theme(axis.text = element_text(hjust = 1, size=6.7, angle=20)) + scale_fill_manual(values=cols)
longset %>% gather(Rate.2013,Rate.2014,Rate.2015, key="yr", value="Rate") %>% mutate(name=reorder(name, Rate)) %>% ggplot(aes(name, Rate, fill=Year)) + geom_col() + scale_fill_manual(values=c("#774F38", mycols3)) + theme_classic() + coord_flip() + labs(x="State", y="Opioid Death Rate", title="Age and population adjusted Opioid Death Rates by State")
longset  %>% mutate(name=reorder(name, Deaths)) %>% ggplot(aes(name, Deaths, fill=Year)) + geom_col() + scale_fill_manual(values=c("#774F38", mycols3)) + theme_classic() + coord_flip() + labs(x="State", y="Opioid Death Counts", title="Opioid Death Raw Counts by State")
```
```{r}
longset %>% gather(Rate.2013,Rate.2014,Rate.2015, key="yr", value="Rate") %>% ggplot(aes(log(Rate), log(Deaths))) + geom_point(alpha=0.9, pch=21)
longset %>% gather(Rate.2013,Rate.2014,Rate.2015, key="yr", value="Rate") %>% ggplot(aes(Rate, Deaths, col=Year)) + geom_point(alpha=0.9, pch=21)
```
```{r}
rates1 <- longset %>% gather(Rate.2013,Rate.2014,Rate.2015, key="yr", value="Rate")
summary(rates1$Rate)
```
```{r}
library(readr)
stategrid <- read.csv("state-grid-coordinates.tsv", stringsAsFactors = FALSE, sep="\t")
head(stategrid)
plot(stategrid$x, stategrid$y, type="n")
text(stategrid$x, stategrid$y, stategrid$state)
stategrid$ysideup <- 12 - stategrid$y
plot(stategrid$x, stategrid$ysideup, type="n")
text(stategrid$x, stategrid$ysideup, stategrid$state)
symbols(stategrid$x, stategrid$ysideup, squares = rep(1, dim(stategrid)[1]), inches=FALSE, asp=1, bty="n", xaxt="n", yaxt="n", xlab="", ylab="")
text(stategrid$x, stategrid$ysideup, stategrid$state)
```
```{r}
head(fullopioiddeathset_2013_2015)
fullopioiddeathset_2013_2015$population <- as.numeric(fullopioiddeathset_2013_2015$population)
```

```{r}
fullopioiddeathset_2013_2015%>% ggplot(aes(population, Deaths.2015)) + geom_point(aes(size=Rate.2015, col=region), alpha=0.5) + theme_classic()
```
```{r}
longset$popoverarea <- as.numeric(longset$population)/as.numeric(longset$area)
summary(100*(longset$popoverarea))
longset$highdense <- longset$popoverarea
longset$highdense <- ifelse(longset$popoverarea > 230, "Dense","NotDense")
fullopioiddeathset_2013_2015$Change.2014.2015 <- 
  100*((fullopioiddeathset_2013_2015$Rate.2015/fullopioiddeathset_2013_2015$Rate.2014)-1)

table(fullopioiddeathset_2013_2015$Significant)

longset$population <- as.numeric(longset$population)
DF <- fullopioiddeathset_2013_2015 %>% right_join(longset,by = c("state", "Range.2015", "Rate.2015", "name", "region", "division", "capital", "area", "population", "Rate.2014", "Range.2014", "Rate.2013", "Range.2013", "Change", "Significant"))

interested.names <- c("Change.2014.2015","Significant","Change", "highdense", "name", "region", "Deaths.2015", "Deaths.2015")
finalDF <- unique(DF[interested.names])
sample( c(1:10) , 51 , replace=T)

fullopioiddeathset_2013_2015$Change.2014.2015 <- 
  100*((fullopioiddeathset_2013_2015$Rate.2015/fullopioiddeathset_2013_2015$Rate.2014)-1)
fullopioiddeathset_2013_2015$Change.2013.2014 <- 
  100*((fullopioiddeathset_2013_2015$Rate.2014/fullopioiddeathset_2013_2015$Rate.2013)-1)
```
```{r}
dffff <- fullopioiddeathset_2013_2015 %>% gather(Change.2013.2014, Change.2014.2015, key="YearChange", val="Percentage")
length(dffff$YearChange)
# dffff %>% select(YearChange, Percentage)

n <- 5
a<- rep(1:9, each=n)
b <- rep(2013:2014, each=51)

dffff$toadd<- c(a,a,1:9, 1, 2,3)
# c <- rep(1:5, each=n)
# d <- rep(1:5, each=n)
# dffff$toadd <- c(a, a, a, a, 5, 6)
length(dffff$toadd)
dffff$numbers <- paste(b, dffff$toadd)
dffff$numbers <- gsub(" ", ".", dffff$numbers)
dffff$numbers <- as.numeric(dffff$numbers)


DFDF <- dffff[c("numbers","Percentage")]
```

```{r}

# dffff$year=sample( c(13:15) , 51 , replace=T)
#  changes2=data.frame(name=finalDF$name, Region=finalDF$region, Change=finalDF$Change.,Year=sample( c(1:10) , 51 , replace=T), Significant=finalDF$Significant) 
# # Plotly library
# library(plotly)
Deaths <- c(fullopioiddeathset_2013_2015$Deaths.2013, fullopioiddeathset_2013_2015$Deaths.2015)
# # Make the graph
# my_graph=plot_ly(x=b, y=a , mode="markers" , size=abs(a), color=ifelse(a>0,"red","green") )
#  
#Change hover mode in the layout argument :
# newdf <- rbind(changes2, changes)
# newdf$Deaths <- Deaths
# summary(newdf$Change)
DFDF %>% ggplot(aes(numbers, Percentage)) + geom_point(aes(size=abs((dffff$Percentage -.0001)*2901), col=ifelse(Percentage > 0, "grey", "maroon")), alpha=0.2) + geom_vline(xintercept = c(2013,2014, 2015), lty="dotted") + geom_hline(yintercept = c(0), alpha=0.7) + theme_classic() + geom_point(aes(size=abs((Percentage-.0001)*2999), col=ifelse(Percentage > 0, "grey", "maroon")), pch=21, alpha=0.9) + theme(legend.position = "none", axis.ticks.x = element_blank(), axis.text.x = element_blank()) + labs(x="", y= "% Change in Opioid Death Rate", subtitle="              2013-2014                                                             2014-2015", title="% Change in Opioid Death Rates ") + ylim(-70,150) 
```

```{r message=FALSE, warning=FALSE}

my_mean=aggregate(longset$Deaths , by=list(longset$region) , mean) ; colnames(my_mean)=c("region" , "mean")
my_sd=aggregate(longset$Deaths  , by=list(longset$region) , sd) ; colnames(my_sd)=c("region" , "sd")
my_info=merge(my_mean , my_sd , by.x=1 , by.y=1)
 
# Make the plot
ggplot(longset) + 
        geom_point(aes(x = region, y = Deaths, size=Deaths) , colour=rgb(0,1,0.60,0.34), alpha=0.2) + 
        geom_point(data = my_info, aes(x=region , y = mean) , colour = rgb(0.7,0.6,0.9,0.7) , size = 8) +
        geom_errorbar(data = my_info, aes(x = region, y = sd, ymin = mean - sd, ymax = mean + sd), colour = rgb(0.4,0.8,0.2,0.4) , width = 0.7 , size=1.5) + ggtitle("Range of Opioid.Deaths by US Demographic Region, 2013-2015") + theme_classic()
df <- longset %>% dplyr::select(name, Year, region, Deaths)
unique(df) %>% ggplot(aes(x=reorder(name,Deaths),y=Deaths, fill=Year)) + geom_col(col="white", alpha=0.8) + labs(title="Opioid Deaths 2013 - 2015", x="State", y="Deaths") + coord_flip() + theme_classic() +
        theme(axis.text = element_text(hjust = 1, size=7, angle=1)) + scale_fill_manual(values=c("#ce1256", "#980043", "#67001f"))
```

```{r}

overdosegrid <- fullopioiddeathset_2013_2015 %>% merge(stategrid, by="state")
symbols(overdosegrid$x, overdosegrid$ysideup,
        squares = rep(1, dim(overdosegrid)[1]),
        inches=FALSE,
        asp=1,
        bty="n",
        xaxt="n", yaxt="n",
        xlab="", ylab="",
        bg=overdosegrid$col,
        fg="#ffffff")
labeltext <- paste(overdosegrid$state, "\n", format(overdosegrid$Rate.2015, 2), sep="")
text(overdosegrid$x, overdosegrid$ysideup, labeltext, cex=.6, col="black")
```
```{r}
summary(overdosegrid$Rate.2015)
summary(overdosegrid$Rate.2014)
summary(overdosegrid$Rate.2013)
hist(overdosegrid$Rate.2015)
```

```{r}


overdosegrid$col <- sapply(overdosegrid$Rate.2013, function(x) {
    # if (x < 5)
    #   {
    #     col <- "#d4b9da"
    # } else
      if (x < 10) {
    #     col <- "#c994c7"
    # } else if (x < 10) {
        col <- "#df65b0"
    } else if (x < 15) {
        col <- "#e7298a"
    } else if (x < 20) {
        col <- "#ce1256"
    } else if (x < 25) {
        col <- "#980043"
    } else {
        col <- "#67001f"
    }
    return(col)
})
# Start layout.
par(mar=c(0,0,0,0), bg="white")
plot(0:1, 0:1, type="n", xlab="", ylab="", axes=FALSE, asp=1)
# Draw map like before.
par(new=TRUE, plt=c(0, 1, 0, 1))
symbols(overdosegrid$x, overdosegrid$ysideup,
        squares = rep(1, dim(overdosegrid)[1]),
        inches=FALSE,
        asp=1,
        bty="n",
        xaxt="n", yaxt="n",
        xlab="", ylab="",
        bg=overdosegrid$col,
        fg="#ffffff")
labeltext <- paste(overdosegrid$state, "\n", format(overdosegrid$Rate.2013, 2), sep="")
text(overdosegrid$x, overdosegrid$ysideup, labeltext, cex=.8, col="#ffffff")
# Legend
par(new=TRUE, plt=c(0, 1, .9, 1))
plot(0, 0, type="n", xlim=c(0, 1), ylim=c(-.1,1), xlab="", ylab="", axes=FALSE)
rect(xleft = c(.4, .45, .5, .55, .6)-.025,
xright = c(.45, .5, .55, .6, .65)-.025,
ybottom = c(0,0,0,0,0)+.1, ytop=c(.2, .2, .2, .2, .2)+.1,
col=c("#df65b0", "#e7298a", "#ce1256", "#980043", "#67001f"),
border="#ffffff", lwd=1)
text(c(.45, .5, .55, .6)-.03, c(0,0,0,0)+.1, labels = c("10", "15", "20", "25"), pos=3, cex=.8)
 #Title




overdosegrid$col <- sapply(overdosegrid$Rate.2015, function(x) {
    # if (x < 5)
    #   {
    #     col <- "#d4b9da"
    # } else
      if (x < 10) {
    #     col <- "#c994c7"
    # } else if (x < 10) {
        col <- "#df65b0"
    } else if (x < 15) {
        col <- "#e7298a"
    } else if (x < 20) {
        col <- "#ce1256"
    } else if (x < 25) {
        col <- "#980043"
    } else {
        col <- "#67001f"
    }
    return(col)
})
# Start layout.
par(mar=c(0,0,0,0), bg="white")
plot(0:1, 0:1, type="n", xlab="", ylab="", axes=FALSE, asp=1)
# Draw map like before.
par(new=TRUE, plt=c(0, 1, 0, 1))
symbols(overdosegrid$x, overdosegrid$ysideup,
        squares = rep(1, dim(overdosegrid)[1]),
        inches=FALSE,
        asp=1,
        bty="n",
        xaxt="n", yaxt="n",
        xlab="", ylab="",
        bg=overdosegrid$col,
        fg="#ffffff")
labeltext <- paste(overdosegrid$state, "\n", format(overdosegrid$Rate.2015, 2), sep="")
text(overdosegrid$x, overdosegrid$ysideup, labeltext, cex=.8, col="#ffffff")
# Legend
par(new=TRUE, plt=c(0, 1, .9, 1))
plot(0, 0, type="n", xlim=c(0, 1), ylim=c(-.1,1), xlab="", ylab="", axes=FALSE)
rect(xleft = c(.4, .45, .5, .55, .6)-.025,
xright = c(.45, .5, .55, .6, .65)-.025,
ybottom = c(0,0,0,0,0)+.1, ytop=c(.2, .2, .2, .2, .2)+.1,
col=c("#df65b0", "#e7298a", "#ce1256", "#980043", "#67001f"),
border="#ffffff", lwd=1)
text(c(.45, .5, .55, .6)-.03, c(0,0,0,0)+.1, labels = c("10", "15", "20", "25"), pos=3, cex=.8)
 #Title

```
```{r dpi=300}
library(tidyverse)
alluv <- longset %>% dplyr::group_by(highdense, region, Significant) %>% tally()

library(alluvial)
cols <- c("#73c6b6", "#772877", "#7C821E", "#D8B98B", "#7A4012", "#c6d4e1", "#2f2016", "#fcfaea", "#456789", "#F0B27A", "black")
# cols<- c("#c6d4e1", "#2f2016", "#fcfaea", "#456789", "#772877", "#7C821E", "#D8B98B", "#2f2016","#c6d4e1", "#C3D938", "#7A4012") ## 11

alluvial(alluv[1:3], freq=alluv$n, alpha=0.68, xw=0.2,cex.axis=0.8, cex = 0.6, blocks=T, border="white",col = ifelse(alluv$Significant == "Significant", "maroon", "grey"))

```
